DEBUG: True
  # !-!-! Change in production !-!-!
  SECRET_KEY: PLEASE_CHANGE_ME
  SECURITY_PASSWORD_SALT: PLEASE_CHANGE_ME
  
  # ==> Set the username, password, host, port and schema correctly!
  #SQLALCHEMY_DATABASE_URI :  mysql://hoyoul:1111@127.0.0.1/flask?charset=utf8mb4
  SQLALCHEMY_DATABASE_URI :  mysql://hoyoul:1111@3.143.230.8/flask?charset=utf8mb4
  SQLALCHEMY_BINDS :
    
  
  #FLASK_USER_SETTINGS : mysql://hoyoul:1111@127.0.0.1/USER?charset=utf8mb4  
  FLASK_USER_SETTINGS : mysql://hoyoul:1111@3.143.230.8/USER?charset=utf8mb4

  INFLUX_URIS : {}
    #S1 : "http://<ip1>:8086/query?pretty=true&db=tickstore&q=SELECT%20*%20FROM%20trade%20WHERE%20symbol=%27KIS_KOSPI200_IDX%27%20ORDER%20BY%20time%20DESC%20LIMIT%201%20tz(%27Asia/Seoul%27)&epoch=s"

  SYNCTHING_DEVICES : {}
    #Dev1 : "<id1>"

  OAUTH_AZURE_APP : "<app/tenant_id>"
  OAUTH_AZURE_KEY : "<secret_id>"
  OAUTH_AZURE_AUTH_URL : https://login.microsoftonline.com/<app/tenant_id>/oauth2/v2.0/authorize
  OAUTH_AZURE_TOKEN_URL : https://login.microsoftonline.com/<app/tenant_id>/oauth2/v2.0/token
  OAUTH_AZURE_BASE_URL : https://graph.microsoft.com/
  OAUTH_AZURE_SCOPE : openid email profile

  STATUS_ENDPOINTS: {}
    #Strat1 : http://<ip>:<port>/<status_path>

  CONTACTS:
    A: 010-9328-3132
    
  BABEL_DEFAULT_LOCALE: "en"
  BABEL_DEFAULT_TIMEZONE: "Asia/Seoul"