---
  DEBUG: True
  # !-!-! Change in production !-!-!
  SECRET_KEY: PLEASE_CHANGE_ME
  SECURITY_PASSWORD_SALT: PLEASE_CHANGE_ME
  
  # ==> Set the username, password, host, port and schema correctly!
  SQLALCHEMY_DATABASE_URI :  mysql://root:1111@127.0.0.1/flask_website?charset=utf8mb4
  #SQLALCHEMY_DATABASE_URI :  mysql://hoyoul:1111@18.223.3.53/flask?charset=utf8mb4
  SQLALCHEMY_BINDS :    
    AUDIT: mysql://root:1111@127.0.0.1/audit?charset=utf8mb4 
  
    
  
  FLASK_USER_SETTINGS : mysql://root:1111@127.0.0.1/USER?charset=utf8mb4  
  #FLASK_USER_SETTINGS : mysql://hoyoul:1111@18.223.3.53/USER?charset=utf8mb4

  SYNCTHING_DEVICES : {}
    #Dev1 : "<id1>"

  OAUTH_AZURE_APP : "<app/tenant_id>"
  OAUTH_AZURE_KEY : "<secret_id>"
  OAUTH_AZURE_AUTH_URL : https://login.microsoftonline.com/<app/tenant_id>/oauth2/v2.0/authorize
  OAUTH_AZURE_TOKEN_URL : https://login.microsoftonline.com/<app/tenant_id>/oauth2/v2.0/token
  OAUTH_AZURE_BASE_URL : https://graph.microsoft.com/
  OAUTH_AZURE_SCOPE : openid email profile

  STATUS_ENDPOINTS: {}
    #Strat1 : http://<ip>:<port>/<status_path>

  CONTACTS:
    A: 010-9328-3132
    
  BABEL_DEFAULT_LOCALE: "en"
  BABEL_DEFAULT_TIMEZONE: "Asia/Seoul"